In [168]:
import numpy as np

In [169]:
input_vectors = [np.array([1,1,1]), np.array([1,0,1]), np.array([0,1,1]), np.array([0,0,1])]
input_vectors

[array([1, 1, 1]), array([1, 0, 1]), array([0, 1, 1]), array([0, 0, 1])]

In [170]:
truth_table = {"input_vectors": input_vectors, "targets":[1,-1,-1,-1]}

In [171]:
truth_table   #Truth table for the AND gate with binary inputs and binomial outputs

{'input_vectors': [array([1, 1, 1]),
  array([1, 0, 1]),
  array([0, 1, 1]),
  array([0, 0, 1])],
 'targets': [1, -1, -1, -1]}

In [172]:
w1, w2, alpha, b, theta = 0, 0, 1, 0, 0.2   #declare the variables

In [173]:
weights = np.array([w1,w2,b])
weights

array([0, 0, 0])

In [174]:
def compute_new_weights(weights, i):  #function to compute the changes in the weights and finally output the new value

    weights[0] = weights[0] + alpha*truth_table['targets'][i]*truth_table['input_vectors'][i][0]
    weights[1] = weights[1] + alpha*truth_table['targets'][i]*truth_table['input_vectors'][i][1]
    weights[2] = weights[2] + alpha*truth_table['targets'][i]
  
    return weights
    

In [175]:
def compute_y_in(weights,i):   #input to the output node
    return np.sum(weights*truth_table['input_vectors'][i])

In [176]:
def compute_y_out(y_in):    #activation function
    if y_in >= theta: return 1
    elif -theta<= y_in < theta : return 0
    else : return -1

In [177]:
condition = True
y_outs = [0,0,0,0]

epoch = 1
while condition:
    
    for i in range(4):
        y_in = compute_y_in(weights,i)
        y_out = compute_y_out(y_in)
        y_outs[i] = y_out
        
        if y_out != truth_table['targets'][i]:      #If the output predicted by the neural network is equal to target, we don't adjust the weights
            weights = compute_new_weights(weights,i)
    
    if y_outs== truth_table['targets']: 
        condition = False
    
    print(f"After epoch number {epoch}: {weights}")
    epoch+=1
        
        

After epoch number 1: [ 0  0 -1]
After epoch number 2: [ 0  0 -2]
After epoch number 3: [ 0  1 -2]
After epoch number 4: [ 0  1 -3]
After epoch number 5: [ 1  1 -3]
After epoch number 6: [ 1  2 -3]
After epoch number 7: [ 1  2 -4]
After epoch number 8: [ 2  2 -4]
After epoch number 9: [ 2  3 -4]
After epoch number 10: [ 2  3 -4]
