In [13]:
import numpy as np

In [14]:
A = np.array([[-11,-10,5],[5,4,-5],[-20,-20,4]], dtype= 'float64')
print(A)

[[-11. -10.   5.]
 [  5.   4.  -5.]
 [-20. -20.   4.]]


In [15]:
def findEigen(matrix, lambda_name):
    xi = np.array([[1],[1],[1]], dtype = 'float64')
    prev_b = [0,0,0]
    while True:
        yi = np.matmul((matrix),xi)
        xi = yi / np.max(abs(yi))
        a = xi / np.min(abs(xi))
        b = [round(xi[j][0],2) for j in range(3) ]
        if prev_b == [-k for k in b] or prev_b == b:
            print("%s Eigen Vector = "%(lambda_name),b)
            b = np.reshape(np.array(b),(3,1))
            b = b/ np.min(b)
            lambda_ = (b.T@A@b/(b.T@b))[0][0]
            print('Corresponding Eigen Value (%s)--> '%(lambda_name),lambda_)
            return lambda_
        prev_b = b

In [16]:
lambda1 = findEigen(A,'first')

first Eigen Vector =  [-0.0, -0.5, -1.0]
Corresponding Eigen Value (first)-->  -6.0


In [17]:
lambda2 = findEigen(A - lambda1 * np.identity(3),'second')

second Eigen Vector =  [-0.99, 0.99, -1.0]
Corresponding Eigen Value (second)-->  4.033443686237416


Smallest eigen value of the matrix A is the largest eigen value of the A inverse matrix. Hence,

In [18]:
C = np.linalg.pinv(A)
lambda3 = findEigen(C,'third')

third Eigen Vector =  [-1.0, 1.0, -0.0]
Corresponding Eigen Value (third)-->  -1.0
